// src/utils/dynamicStyles.ts
import { StyleSheet } from 'react-native';
import { HallTheme } from '../config/hallThemes';

export const createDynamicStyles = (theme: HallTheme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      height: 56,
      backgroundColor: theme.surface,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.primary,
    },
    headerAddress: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 2,
    },
    headerAddressText: {
      fontSize: 11,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    heroCard: {
      borderRadius: 12,
      padding: 20,
      position: 'relative',
      overflow: 'hidden',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
    heroTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#FFFFFF',
      marginBottom: 6,
    },
    heroSubtitle: {
      fontSize: 13,
      color: 'rgba(255,255,255,0.9)',
      lineHeight: 18,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.primary,
    },
    scheduleCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: theme.surface,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 4,
      elevation: 2,
    },
    serviceCard: {
      backgroundColor: theme.surface,
      width: '48%',
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 4,
      elevation: 2,
    },
    serviceIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.background,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    fab: {
      position: 'absolute',
      right: 24,
      bottom: 100,
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: theme.primary,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 12,
    },
    fabText: {
      fontSize: 32,
      color: '#FFFFFF',
      fontWeight: '300',
    },
    // Add more dynamic styles as needed
  });
};