// src/utils/notifications.ts
// Persistent store for notifications generated by the app (e.g. a technician
// resolving a request). These are merged with the static demo notifications
// shown in the Notification Center.
import AsyncStorage from '@react-native-async-storage/async-storage';

const STORAGE_KEY = 'notifications';

export interface StoredNotification {
  id: string;
  type: 'alert' | 'maintenance' | 'system';
  title: string;
  message: string;
  time: string; // display string, e.g. "Just now"
  createdAt: string; // ISO timestamp
  isRead: boolean;
  isNew?: boolean;
  icon: string;
  category?: string;
  description?: string;
  status?: string;
  technician?: { name: string; role: string; online: boolean };
}

export const getNotifications = async (): Promise<StoredNotification[]> => {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch (error) {
    console.log('Error loading notifications:', error);
    return [];
  }
};

export const saveNotifications = async (list: StoredNotification[]): Promise<void> => {
  try {
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(list));
  } catch (error) {
    console.log('Error saving notifications:', error);
  }
};

// Adds a notification to the top of the store (newest first).
export const addNotification = async (notification: StoredNotification): Promise<void> => {
  const existing = await getNotifications();
  await saveNotifications([notification, ...existing]);
};

// Marks a stored notification as read (no-op if it isn't a stored one).
export const markNotificationRead = async (id: string): Promise<void> => {
  const existing = await getNotifications();
  if (!existing.some(n => n.id === id)) return;
  await saveNotifications(existing.map(n => (n.id === id ? { ...n, isRead: true, isNew: false } : n)));
};

export const clearNotifications = async (): Promise<void> => {
  await saveNotifications([]);
};
